### ISSUE TITLE
Content issues - all the content is default ones.

### ISSUE THREAD

**Issue by setco-website** [praveenscience/Synergia-HackFest-2023#1]
Can we please change the following?

1. Change the title in a good way, example: **Synergia HackFest 2023**.
2. Add some info in the body content, covering what all we are covering: Synergia HackFest 2023: Opening Ceremony & How to contribute to Open Source by Praveen Kumar.

I guess I can fix this, so can you please assign this to me.

**Comment by praveenscience** [comment]
Nice, this is amazing... Go ahead and fix it.

**Comment by setco-website** [comment]
Okay sure, I am working on it. Will be done with this in few seconds.
